name: Andrasat Nuxt Deployment
run-name: ${{ github.actor }} is building... 🚀
on:
  push:
    branches:
      - main
jobs:
  Semantic-Release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: v0.6.7
      - name: Install Dependencies
        run: bun install
      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: bun run semantic-release
  Build-And-Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Action for DigitalOcean - doctl
        uses: digitalocean/action-doctl@v2.3.0
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Login to Droplet and Pull Main
        run: |
          echo "🚀 Logging into Droplet and Updating Repository"
          doctl compute ssh "$DROPLET_ID" --ssh-command "cd /var/www && git pull origin main"
        env:
          DROPLET_ID: ${{ secrets.DROPLET_ID }}
      - name: Install Dependencies
        run: |
          echo "🚀 Installing Dependencies"
          doctl compute ssh "$DROPLET_ID" --ssh-command "cd /var/www/andrasat-nuxt && bun install"
      - name: Build App
        run: |
          echo "🚀 Building App"
          doctl compute ssh "$DROPLET_ID" --ssh-command "cd /var/www/andrasat-nuxt && bun run build"
      - name: Run App
        run: |
          echo "🚀 Running App"
          doctl compute ssh "$DROPLET_ID" --ssh-command "cd /var/www/andrasat-nuxt && bun run ./output/server/index.mjs"
