name: Andrasat Nuxt - Release
run-name: ${{ github.actor }} is building... 🚀
on:
  push:
    branches:
      - main
jobs:
  Semantic-Release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.36
      - name: Install Dependencies
        run: bun install
      - name: Semantic Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: bun run semantic-release
