name: Andrasat Nuxt Deployment
run-name: ${{ github.actor }} building... 🚀
on:
  push:
    branches:
      - main
jobs:
  Semantic-Release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm install
      - name: Semantic Release
        run: npx semantic-release
  Build-And-Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Action for DigitalOcean - doctl
        uses: digitalocean/action-doctl@v2.3.0
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Login to Droplet and Pull Main
        run: |
          echo "🚀 Logging into Droplet and Updating Repository"
          doctl compute ssh default --ssh-command "cd /var/www && git pull origin main"
      - name: Install Dependencies
        run: |
          echo "🚀 Installing Dependencies"
          doctl compute ssh default --ssh-command "cd /var/www/andrasat-nuxt && bun install"
      - name: Build App
        run: |
          echo "🚀 Building App"
          doctl compute ssh default --ssh-command "cd /var/www/andrasat-nuxt && bun run build"
      - name: Run App
        run: |
          echo "🚀 Running App"
          doctl compute ssh default --ssh-command "cd /var/www/andrasat-nuxt && bun run ./output/server/index.mjs"
